import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import ShareState from "@/components/shared/context/share-state";

export const metadata = {
  title: "WeatherWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider className="default relative">
          <ShareState>
            <main className="bg-primary h-auto min-h-screen">
              {children}
            </main>
          </ShareState>
        </NextUIProvider>
      </body>
    </html>
  );
}
