import "./globals.css";
import ShareState from "@/components/shared/context/share-state";
import InnerLayout from "@/components/shared/inner-layout";

export const metadata = {
  title: "WeatherWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ShareState>
            <InnerLayout>
              {children}
            </InnerLayout>
        </ShareState>
      </body>
    </html>
  );
}


