import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import ShareState from "@/components/shared/context/share-state";
import SideBar from "@/components/layout/sidebar";

export const metadata = {
  title: "WeatherWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider className="default relative">
          <ShareState>
            <main className="bg-primary grid grid-cols-layout min-h-screen p-6 gap-6">
              <SideBar />
              {children}
            </main>
          </ShareState>
        </NextUIProvider>
      </body>
    </html>
  );
}
